[project]
name = "django_adjango"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "django==5.0.1",
    "gunicorn==21.2.0",
    "uvicorn==0.27.0",
]
